// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDJCq-CIxAYxLhzgqSw0gXDc8WJ8kvGSg',
    appId: '1:70960843399:web:c74769555ad3a90b1c0622',
    messagingSenderId: '70960843399',
    projectId: 'crafty-helper-382108',
    authDomain: 'crafty-helper-382108.firebaseapp.com',
    storageBucket: 'crafty-helper-382108.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7JRCbTPLylIQ6x-qhkpX0N2twIz5eIbs',
    appId: '1:70960843399:android:7e7e89c8645ca88c1c0622',
    messagingSenderId: '70960843399',
    projectId: 'crafty-helper-382108',
    storageBucket: 'crafty-helper-382108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhgYaCGnd_6_2EDNLX3yBPwTv-0Luu4Z8',
    appId: '1:70960843399:ios:55b6ed7c11519b611c0622',
    messagingSenderId: '70960843399',
    projectId: 'crafty-helper-382108',
    storageBucket: 'crafty-helper-382108.appspot.com',
    iosClientId: '70960843399-3utv59004g10bjjidhk694r1nojqqu7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.ealert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhgYaCGnd_6_2EDNLX3yBPwTv-0Luu4Z8',
    appId: '1:70960843399:ios:55b6ed7c11519b611c0622',
    messagingSenderId: '70960843399',
    projectId: 'crafty-helper-382108',
    storageBucket: 'crafty-helper-382108.appspot.com',
    iosClientId: '70960843399-3utv59004g10bjjidhk694r1nojqqu7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.ealert',
  );
}
